In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:

# Load the dataset
data = pd.read_csv('./data/data-ready.csv')

# Features and target
features = data[['Temperature', 'Humidity', 'Wind Speed', 'general diffuse flows', 'diffuse flows', 'Year', 'IsWeekend', 'IsNight', 'HourCos', 'HourSin', 'MonthCos', 'MonthSin', 'DayCos', 'DaySin']]
target = data['z1']

# Normalize the features
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)

# Bin the target variable (EnergyConsumption) into quartiles
target_binned = pd.qcut(target, q=4, labels=False)

In [4]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_scaled, target_binned, test_size=0.2, random_state=42)

# Define the Naive Bayes model
nb_model = GaussianNB()

# Train the model
nb_model.fit(X_train, y_train)

# Make predictions
y_pred = nb_model.predict(X_test)

In [5]:

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Classification report
report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{report}')

# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')


Accuracy: 0.6280045784051889
Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.94      0.79      2607
           1       0.59      0.20      0.30      2630
           2       0.54      0.61      0.57      2585
           3       0.66      0.76      0.71      2662

    accuracy                           0.63     10484
   macro avg       0.62      0.63      0.59     10484
weighted avg       0.62      0.63      0.59     10484

Confusion Matrix:
[[2439  148   16    4]
 [ 955  531  811  333]
 [  66  216 1579  724]
 [  75    9  543 2035]]
